name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
      ip:
        type: string
        required: true
      username:
        type: string
        required: true
      path:
        type: string
        required: false

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ github.event.inputs.ip }}
          username: ${{ github.event.inputs.username }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            whoami
            ls -al
