name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
      ip:
        type: string
        required: true
      username:
        type: string
        required: true
      
env:
  IP: ${{ github.event.inputs.ip }}
  USERNAME: ${{ github.event.inputs.username }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: $IP
          username: $USERNAME
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            whoami
            ls -al
